### ISSUE TITLE
Show credit to https://github.com/wong2/chatgpt-google-extension

### ISSUE THREAD

**Issue by wong2** [shobrook/ChatOverflow#3]
Apparently you're borrowing code from https://github.com/wong2/chatgpt-google-extension so it would be nice to give credit.

**Comment by jthoward64** [comment]
Give that [wong2/chatgpt-google-extension](https://github.com/wong2/chatgpt-google-extension) is GPL 3 and this project is unlicensed (which [implies](https://choosealicense.com/no-permission) all rights reserved) I think it's actually illegal

From the GPL:

>   5. Conveying Modified Source Versions.
> 
>   You may convey a work based on the Program, or the modifications to
> produce it from the Program, in the form of source code under the
> terms of section 4, provided that you also meet all of these conditions:
> 
>     a) The work must carry prominent notices stating that you modified
>     it, and giving a relevant date.
> 
>     b) The work must carry prominent notices stating that it is
>     released under this License and any conditions added under section
>     7.  This requirement modifies the requirement in section 4 to
>     "keep intact all notices".
> 
>     c) You must license the entire work, as a whole, under this
>     License to anyone who comes into possession of a copy.  This
>     License will therefore apply, along with any applicable section 7
>     additional terms, to the whole of the work, and all its parts,
>     regardless of how they are packaged.  This License gives no
>     permission to license the work in any other way, but it does not
>     invalidate such permission if you have separately received it.
> 
>     d) If the work has interactive user interfaces, each must display
>     Appropriate Legal Notices; however, if the Program has interactive
>     interfaces that do not display Appropriate Legal Notices, your
>     work need not make them do so.
> 
>   A compilation of a covered work with other separate and independent
> works, which are not by their nature extensions of the covered work,
> and which are not combined with it such as to form a larger program,
> in or on a volume of a storage or distribution medium, is called an
> "aggregate" if the compilation and its resulting copyright are not
> used to limit the access or legal rights of the compilation's users
> beyond what the individual works permit.  Inclusion of a covered work
> in an aggregate does not cause this License to apply to the other
> parts of the aggregate.

>   8. Termination.
> 
>   You may not propagate or modify a covered work except as expressly
> provided under this License.  Any attempt otherwise to propagate or
> modify it is void, and will automatically terminate your rights under
> this License (including any patent licenses granted under the third
> paragraph of section 11).
> 
>   However, if you cease all violation of this License, then your
> license from a particular copyright holder is reinstated (a)
> provisionally, unless and until the copyright holder explicitly and
> finally terminates your license, and (b) permanently, if the copyright
> holder fails to notify you of the violation by some reasonable means
> prior to 60 days after the cessation.
> 
>   Moreover, your license from a particular copyright holder is
> reinstated permanently if the copyright holder notifies you of the
> violation by some reasonable means, this is the first time you have
> received notice of violation of this License (for any work) from that
> copyright holder, and you cure the violation prior to 30 days after
> your receipt of the notice.
> 
>   Termination of your rights under this section does not terminate the
> licenses of parties who have received copies or rights from you under
> this License.  If your rights have been terminated and not permanently
> reinstated, you do not qualify to receive new licenses for the same
> material under section 10.

**Comment by shobrook** [comment]
Done. Also added a MIT License.

**Comment by josStorer** [comment]
@tajetaje  In fact, it's legal. wong2's repository was originally open-sourced under the MIT license and later changed to GPL3 (https://github.com/wong2/chatgpt-google-extension/commit/62276f1464c915dc462a63133a20d451b2837ac1), and this repository is actually based on the MIT part.

By the way, @wong2 , you seem to have created issues in multiple repositories asking them to add your project, while you removed your inspiration source (https://github.com/wong2/chatgpt-google-extension/commit/c54528b0e13058ab78bfb433c92603db017d1b6b). I think this is somewhat unethical. Additionally, after benefiting from the community, you closed the issues of your repository, making all the issues no longer publicly traceable, and your project no longer has any feedback channels. Moreover, you seem to be very eager to monetize, charging $400 a day for advertising fees. However, for many issues and feature requests raised by the community, you kept the issues open and followed up for several months but completely ignored them and then closed them. I am deeply dissatisfied with this.

I'm sorry for venting my emotions in this possibly unrelated repository.
